### ISSUE TITLE
CI and svglite

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/tinysnapshot#11]
Stoked to see this on CRAN!

In the README you suggest setting `options(tinysnapshot_device = "svglite")` to overcome small differences across OS's and machines during CI.

Just to flag that I'm still running into problems with this approach over [here](https://github.com/grantmcdermott/ggiplot/actions/runs/4579920638). (In this particular case, the MacOs run is working, since that's what I use to write the original SVG plots. But the rest are failing.) FWIW I set the `svglite` option at the top of test script [here](https://github.com/grantmcdermott/ggiplot/blob/main/inst/tinytest/test_ggiplot.R#L4).

Feel free to close this issue immediately if it is just annoying, since you already suggest the ultimate workaround of hiding my test suite. But I thought you might be interested in feedback from actual use cases.

**Comment by vincentarelbundock** [comment]
Thanks, that's helpful.

A real solution to this would be to ship my own `svglite()` and fonts like `vdiffr`, but that would require figuring out a bunch of C++ stuff, and I don't have the bandwidth for that.

I just pushed a commit to Github that makes it easier to only run tests on a specific OS. With the dev version you can now do:

```r
options(tinysnapshot_os = "Darwin")
options(tinysnapshot_device = "svglite")
```

Then, `expect_snapshot_plot()` will return an invisible `NULL`. Obviously not idea, but easier than writing a bunch of `if{}` or `exit_file()`.

**Comment by grantmcdermott** [comment]
Excellent, thanks! Happy to close preemptively. Will reopen if I still run into problems once I'm able to test from my laptop.
