### ISSUE TITLE
Support error messages in `expect_snapshot_print()`?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/tinysnapshot#12]
Hi Vincent, I'd like to use `tinysnapshot` for error messages created by `rlang::abort()` (because the `pattern` arg of `tinytest::expect_error()` doesn't work with them):

 ``` r
foo <- function() dplyr::select(iris, foo)
foo()
#> Error in `dplyr::select()`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `foo` doesn't exist.
#> Backtrace: [CUT]

tinytest::expect_error(
  foo(),
  pattern = "Can't subset"
)
#> ----- FAILED[xcpt]: <-->
#>  call| tinytest::expect_error(foo(), pattern = "Can't subset")
#>  diff| The error message:
#>  diff| ''
#>  diff| does not match pattern 'Can't subset'
```

However, it seems that `expect_snapshot_print()` can't capture error messages.

**inst/tinytest/test_snapshoterror.R**

```r
using("tinysnapshot")

foo <- function() dplyr::select(iris, foo)

tinysnapshot::expect_snapshot_print(
  foo(),
  label = "select-error"
)
```

Run `tinytest::test_all()`:

```r
test_snapshoterror.R..........    0 tests    Error in `dplyr::select()` at test_snapshoterror.R:3:7:
! Can't subset columns that don't exist.
✖ Column `foo` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
```

Is it something that could be implemented? Or maybe I missed something?

**Comment by vincentarelbundock** [comment]
I don’t know the `rlang` error objects well, but the first problem seems to be that `tryCatch()$message` returns an empty string, which is the “standard” output that we should expect in R, but isn’t respected by `rlang`. The result of this non-conformity is that `tinytest` doesn’t see the `rlang` message. It’s pretty easy to hack our way into extracting and testing the full error message directly with `tinytest`. This is what I recommend, as this doesn’t seem like a “snapshot” kind of problem (unless what you really want to test is the formatting of error messages, but that seems like a small use-case). What we really want here is the basic `expect_error` to work with `rlang`, so I think this should be fixed upstream in `tinytest`. In the meantime, maybe you can make something like this work:

``` r
library(tinytest)

foo <- function() dplyr::select(iris, foo)

rlang_to_base <- function(f) {
    msg <- paste(capture.output(print(tryCatch(f(), error = function(e) e), collapse = "\n")))
    stop(msg)
}

expect_error(rlang_to_base(foo), "Can't subset")
# ----- PASSED      : <-->
#  call| expect_error(rlang_to_base(foo), "Can't subset")
```

**Comment by etiennebacher** [comment]
I see, thanks. I'll play a bit with this and maybe open an issue in tinytest repo to support rlang errors

**Comment by vincentarelbundock** [comment]
Yeah, I think it would be pretty easy to make this work with `tinytest` without adding any dependencies to that package. Basically, just use `inherits` to check if the error is a `rlang` class, extract the error message somehow, and then keep going on our merry way. See here in particular:

https://github.com/markvanderloo/tinytest/blob/master/pkg/R/expectations.R#L548
