### ISSUE TITLE
expect_snapshot_plot fails in platforms other than windows

### ISSUE THREAD

**Issue by marcboschmatas** [vincentarelbundock/tinysnapshot#15]
I'm developing a ggplot extension (you can find the code [here](https://github.com/marcboschmatas/ggspark/tree/master)), and expect_snapshot_plot fails when testing in rhub with platforms other than windows (see [here](https://github.com/r-hub2/strong-kangaroo-ggspark/actions/runs/9017640846) for test results). In concrete, I get the following error.

```
 test-plot.R...................    1 tests 1 fails 0.7s
----- FAILED[]: test-plot.R<19--19>
 call| expect_snapshot_plot(p, label = "ggplot2_example")
 diff| 21712
 info| Diff plot saved to: _tinysnapshot_review/ggplot2_example.png
Error: 1 out of 1 tests failed
```

I cannot underestand why this is happening. The test I am running is this one

```

source("helpers.R")
using("tinysnapshot")
library(ggplot2)


p <- ggplot(airquality, aes(Day, Wind, group = Month)) + 
  stat_interquartilerange(geom = "ribbon",
                          show.legend = FALSE) +
  geom_line() + 
  stat_sparklabels(geom = "label", label_fun = \(x) round(x, 0),
                   show.legend = FALSE) +
  scale_y_continuous(limits = c(0, 25)) + 
  facet_grid(Month~.) +
  ggtitle("Daily wind intensity by month in NYC") +
  theme_minimal()


expect_snapshot_plot(p, label = "ggplot2_example")
```

**Comment by vincentarelbundock** [comment]
On what OS did you generate the plots? Might be related to the discussion in the readme about "CRAN, continuous integration, and deterministic plots"

**Comment by marcboschmatas** [comment]
On Windows 11. Plus, the plot saved in the _tinysnapshot does not look like a theme_minimal plot
![ggplot2_example](https://github.com/vincentarelbundock/tinysnapshot/assets/64325179/f1662173-a725-4c92-9a5a-bc10853c0beb)

**Comment by marcboschmatas** [comment]
Solved it with the instructions in the description, so we can call it closed. Thanks a lot!

**Comment by vincentarelbundock** [comment]
Great news!

The other thing I'll note is that tinysnapshot applies ggplot2::theme_test() to all images before saving, so that explains why your images look different than theme_minimal().

For what it's worth, I generally think it is not ideal for package developers to pre-apply ggplot2 themes automatically, because it makes some customizations more difficult and less predictable for users. YMMV, of course.
